### ISSUE TITLE
Update for BO4 CWL?

### ISSUE THREAD

**Issue by tycox94** [Activision/cwl-data#18]
What causes this data to get updated, and can we reach out to an API to get it regularly?

**Comment by saturnboy** [comment]
@tycox94 I upload the data to github manually (by making a commit, and pushing it).  For example, I just pushed the very first release of BO4 data today in commit e2e1d77686e1277c0af1c07193dd44f6e37dfb72.  Data is only uploaded every 2 weeks or so.  Easiest to just clone the repo, probably not worth the effort to grab it programmatically via the Github API (but it can be done).
